<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="**/*.cs" />
    <Compile Include="Program.cs" />
    <Compile Include="Concepts\01_WhatIsNull.cs" />
    <Compile Include="Concepts\02_NullableValueTypes.cs" />
    <Compile Include="Concepts\03_NullableReferenceTypes.cs" />
  </ItemGroup>
</Project>
